### ISSUE TITLE
Error in implementation of Trompt

### ISSUE THREAD

**Issue by AlfredTino** [yandex-research/tabred#1]
Position: Model class in bin/trompt.py
Here, you only create one TromptCell for all cycles.

**Comment by puhsu** [comment]
Hi! I see the problem, I did a quick rerun on one dataset for now and this seem to matter. Working on a fix and an update right now.

**Comment by puhsu** [comment]
Hi! We've fixed the trompt implementation and rerun it an all datasets. The performance improved, we've also updated the paper with these new results for trompt
